name: Health check

on:
  schedule:
    - cron:  '0 12 1 * *'
  
jobs:
  run_health_check:
    runs-on: ubuntu-20.04
    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v4
      with:
        url: https://full-stack-open-pokedex-cool-sound-7678.fly.dev/

