name: Deployment pipeline

env:
  CONTAINS_SKIP: ${{ contains(github.event.head_commit.message, '#skip') }}
  COMMIT_URL: ${{ github.event.head_commit.url }}
  COMMIT_AUTHOR: ${{ github.event.head_commit.author }}

on:
  push:
    branches:
      - main
  pull_request:    
    branches: [main]    
    types: [opened, synchronize]


jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Make productuion build
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push'}}
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: npm install
      - run: npm run build
      - run: flyctl deploy --remote-only
        if: ${{ env.CONTAINS_SKIP == 'false' }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Deployment Success
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'An new version of PokeDex deployed by ${{ env.COMMIT_AUTHOR }}'
      - name: Deployment Failure
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Build failed: commit ${{ env.COMMIT_URL }} by ${{ env.COMMIT_AUTHOR }} broke the build :('


  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch